### ISSUE TITLE
Returning `dtype` or `device` from jitted function returns thunder's dtype or device (not torch.{dtype/device}).

### ISSUE THREAD

**Issue by kshitij12345** [Lightning-AI/lightning-thunder#573]
I think this can be a problem where part of the program is called with `thunder.jit` and it's output is used for non-compatible parts (eg. https://github.com/Lightning-AI/lightning-thunder/issues/461). These non-compatible parts may expect these objects to be `torch` types.

```python
import thunder
import torch

def foo(x):
    return x.device, x.dtype

jfoo = thunder.jit(foo)
x = torch.randn(4,)
o = jfoo(x)
print(o)  # (cpu, float32)
print(type(o[0]), type(o[1]))  # <class 'thunder.core.devices.Device'> <class 'thunder.core.dtypes.floating'>

print(thunder.last_traces(jfoo)[-1])

# # Constructed by Delete Last Used (took 0 milliseconds)
# import thunder.core.devices as devices
# import thunder.core.dtypes as dtypes
# import torch
# from thunder.executors.torchex import no_autocast

# @torch.no_grad()
# @no_autocast
# def computation():
#   return (devices.Device("cpu"), dtypes.float32)
```

**Comment by k223kim** [comment]
Hi @kshitij12345 , can I ask you why you think #461 is related to this issue (just trying to get a better understanding)? Because, when I reproduced the recursive error by only jitting the encoder of CLIPTextTransformer, it threw an error during the forward pass of the encoder. Doesn't that mean this error is not related to passing non-compatible parts? Would appreciate it if you can correct me if I am interpreting this incorrectly.

**Comment by k223kim** [comment]
@kshitij12345 Thanks for the clarification. It makes better sense now :)

**Comment by mruberry** [comment]
triage review —

- there are several ways we can think of addressing this, the simplest may be to convert all thunder dtype and device outputs to their corresponding torch objects (but this would be incorrect if anyone cared to return the thunder objects, which seems very unlikely)
