### ISSUE TITLE
`saved_tensors_list` might contain `None`s

### ISSUE THREAD

**Issue by nikitaved** [Lightning-AI/lightning-thunder#619]
```
saved_tensors is implemented to store only tensors and nothing else is allowed by torch.autograd.Function's ctx.save_for_backward method.
```

_Originally posted by @IvanYashchuk in https://github.com/Lightning-AI/lightning-thunder/pull/607#discussion_r1643082936_

As per title. https://github.com/Lightning-AI/lightning-thunder/pull/616 shows that this assumption is not true, and fails in our notebooks.

**Comment by IvanYashchuk** [comment]
I was under the impression that `ctx.save_for_backward` doesn't allow non-Tensor objects but it seems it does allow `None`:
```py
import torch

class Test(torch.autograd.Function):
    @staticmethod
    def forward(ctx, x):
        ctx.save_for_backward(None, x, None)
        return x

    @staticmethod
    def backward(ctx, g):
        print(ctx.saved_tensors)
        return g

a = torch.Tensor([1.0]).requires_grad_(True)
aa = Test.apply(a)
aa.backward(aa) # prints (None, tensor([1.], requires_grad=True), None)
```
However, if we put a `float` then we'd hit 
```py
TypeError: save_for_backward can only save variables, but argument 2 is of type float
```

Thank you for checking this with #616! I guess we have a discrepancy between the trace-time types and runtime types because we try to generate a trace that puts only TensorProxies into "saved tensors" list/tuple:
https://github.com/Lightning-AI/lightning-thunder/blob/0dc9807c00bae6076c15a5fdc32a2653fc00e225/thunder/core/transforms.py#L3471-L3484

We need to accept that "saved_tensors" is actually "saved_tensors_and_nones" and whatever code that uses `saved_tensors` needs to check for Nones.
